### ISSUE TITLE
OcaUint64Sensor isn't supported

### ISSUE THREAD

**Issue by walterbrebels** [DeutscheSoft/OCA.js#3]
The OcaUint64Sensor class currently isn't supported.

This is the class definition that is needed:
```
export const OcaUint64Sensor = make_control_class(
    "OcaUint64Sensor",
    5,
    "\u0001\u0001\u0002\u0001\u0009",
    2,
    OcaBasicSensor,
    [
      [ "GetReading", 5, 1, [  ], [ UINT64, UINT64, UINT64 ] ]
    ],
    [
      [ "Reading", [ UINT64 ], 5, 1, false, false, null]
    ],
    [    ]
);
```

**Comment by arneg** [comment]
True! This is an exporting error from the Standards UML files. I will look into it.

Also note that this project has been renamed and moved to https://github.com/DeutscheSoft/AES70.js

**Comment by walterbrebels** [comment]
I saw, I posted it on the wrong project by mistake.
Thank you for looking into it!

**Comment by arneg** [comment]
The issue was/is that the standards document is not formatted correctly, my code generator ended up ignoring the OcaUint64Sensor. I have fixed that and updates AES70.js. Let me know if you have any other issues.
